-- Your SQL goes here
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  unionID VARCHAR NOT NULL,
  openid VARCHAR NOT NULL UNIQUE,
  name VARCHAR NOT NULL,
  derive VARCHAR NOT NULL,
  blank BOOLEAN NOT NULL DEFAULT FALSE
);